# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'

runs:
  using: 'composite'
  steps:
    - name: Build the Docker image
      shell: bash
      env:
        API_KEY: 'myKey'
        # APP_FILE: ${{ inputs.app-file }}

      run: ${{ github.action_path }}/docker-compose-build-images.sh

